#define crypto_scalarmult_base crypto_scalarmult_curve25519_base 
#define crypto_scalarmult crypto_scalarmult_curve25519
#define crypto_stream_xor crypto_stream_salsa20_xor
#define crypto_stream crypto_stream_salsa20

